### PR TITLE
avatar display and performance improvement for Tk client

### PR DESCRIPTION
**Pull request by yangl1996**
## Improvements
* display avatar in member list window (now using Shimakaze
shimakaze
 as default)
* remove unused lines
* improved code structure

## Existing Problems
* 'logout' function is not compatible with server, should close the socket when logout
* should display outbound message directly instead of waiting for the server's echo to improve user experience

### CODE REVIEW

**Comment by Jueast** [comment]
What phenomenon will the first problem cause?
Did the problem exist in former version?

**Comment by yangl1996** [comment]
@Jueast  I tested previous versions and found that the bug was introduced at the very beginning, but remained undiscovered. The result is that if a user presses 'logout' on client, the username is still assigned to the user so he can still send message with this username.

**Comment by Jueast** [comment]
The exit() function in server.py wouldn't reset the name before..now it should be able to do so in ff46ad2ba0cafab31e8bb2e3063704451d3a8d83

**Comment by yangl1996** [comment]
problem 1 fixed in ff46ad2

**Pull request merged**
